name: Build Native Libraries and Binaries

on:
  workflow_dispatch:

jobs:
  build-native:
    runs-on: ubuntu-latest

    env:
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11

    - name: Install required packages and Android SDK command line tools
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip wget build-essential coreutils
        wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip -d $ANDROID_SDK_ROOT
        mkdir -p $ANDROID_SDK_ROOT/cmdline-tools/latest
        shopt -s extglob
        mv $ANDROID_SDK_ROOT/cmdline-tools/!(latest) $ANDROID_SDK_ROOT/cmdline-tools/latest/ || true
        if [ -d "$ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools" ]; then
          mv $ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools/* $ANDROID_SDK_ROOT/cmdline-tools/latest/
          rm -rf $ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools
        fi
        yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT --licenses
        $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platform-tools" "platforms;android-30" "ndk;23.1.7779620"

    - name: Make build-jni.sh executable
      run: chmod +x ./app/src/main/build-jni.sh

    - name: Build native libs and binaries using build-jni.sh
      env:
        ANDROID_SDK_ROOT: ${{ env.ANDROID_SDK_ROOT }}
      run: ./app/src/main/build-jni.sh

    - name: Upload jniLibs artifact (shared libs)
      uses: actions/upload-artifact@v4
      with:
        name: jniLibs
        path: app/src/main/jniLibs/

    - name: Upload binaries artifact (executables)
      uses: actions/upload-artifact@v4
      with:
        name: binaries
        path: app/src/main/bin/
