name: Build JNI SO libs only (ndk-build)

on:
  workflow_dispatch:

jobs:
  build-native:
    runs-on: ubuntu-latest

    env:
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11

    - name: Install Android SDK command line tools
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip wget
        wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip -d $ANDROID_SDK_ROOT
        mkdir -p $ANDROID_SDK_ROOT/cmdline-tools/latest
        shopt -s extglob
        mv $ANDROID_SDK_ROOT/cmdline-tools/!(latest) $ANDROID_SDK_ROOT/cmdline-tools/latest/ || true
        if [ -d "$ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools" ]; then
          mv $ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools/* $ANDROID_SDK_ROOT/cmdline-tools/latest/
          rm -rf $ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools
        fi
        yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT --licenses
        $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platform-tools" "platforms;android-30" "ndk;23.1.7779620"

    - name: Build native libs only
      env:
        ANDROID_SDK_ROOT: ${{ env.ANDROID_SDK_ROOT }}
        PATH: $ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH
      run: |
        echo "Building native libraries with ndk-build only..."
        export NDK_PATH=$ANDROID_SDK_ROOT/ndk/23.1.7779620
        $NDK_PATH/ndk-build -C app/src/main/cpp

    - name: Upload jniLibs artifact
      uses: actions/upload-artifact@v4
      with:
        name: jniLibs
        path: app/src/main/jniLibs/
